version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - .:/api/
    ports:
      - 11702:11702
    depends_on:
      - pgdb
    
  web:
    build: 
      context: ./
      dockerfile: Dockerfile-web
    volumes:
      - ./:/app/
    ports:
      - 11701:11701
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      POSTGRES_DB: "silaeder_projects"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "XAdqjYR79EfDQk6_CzcS5T"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=silaeder_projects@admin.org
      - PGADMIN_DEFAULT_PASSWORD=XAdqjYR79EfDQk6_CzcS5T
    ports:
      - 11703:80
    depends_on:
      - pgdb
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: