version: '3.8'

services:
  web:
    build: ./
    volumes:
      - ./:/app/
    ports:
      - 11701:11701
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      POSTGRES_DB: "silaeder_projects"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "XAdqjYR79EfDQk6_CzcS5T"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=silaeder_projects@admin.org
      - PGADMIN_DEFAULT_PASSWORD=XAdqjYR79EfDQk6_CzcS5T
    ports:
      - 11702:80
    depends_on:
      - pgdb

volumes:
  postgres_data:
